import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { SessionProvider } from "next-auth/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "CSV Viewer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session?.user) {
    redirect("/api/auth/signin?callbackUrl=/");
  }

  return (
    <html lang="en">
      <body className={`${poppins.className} flex`}>
        {/* <pre>{JSON.stringify(session.user, null, 2)}</pre> */}
        <SessionProvider session={session}>
          <Sidebar />
          <div className="p-6 w-full">{children}</div>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
